logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
    '[com.totvs.msmigracaopsdc.api]': DEBUG
    '[org.springframework.boot.context]': DEBUG
server:
  compression:
    enabled: true
  port: 8097
  servlet:
    context-path: /ms-migracao-psdc
springfox:
  documentation:
    swagger.v2.path: /v2/api-docs
    info:
      title: Microsserviço Scheduling Migration
      description: ms-migracao-psdc API Docs.
      version: 1.0
    base-package: com.totvs.msmigracaopsdc.api
spring:
  messages:
    basename: i18n/messages
  datasource:
    platform: oracle
    url: jdbc:oracle:thin:@10.120.0.18:1521:oralin
    username: prdtools
    password: toolsscc
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    database: ORACLE
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle12cDialect
    properties:
      hibernate:
        jdbc:
          lob:
            '[non_contextual_creation]': true
        '[format_sql]': true
        '[use_sql_comments]': true
  task:
    scheduling:
      pool:
        size: 2 